project:
  type: website
  output-dir: docs
  render:
    - "*"
    - "!CHANGELOG.md"
    - "!docs/"

website:
  title: "TEST: Alaska Region Data Management User Guide"
  page-navigation: true

  search:
    location: sidebar
    type: textbox

  sidebar:
    style: docked
    background: light
    contents: auto
#    contents:    
#      - alaska-data-management-101/*
#      - planning/index.md
#      
#      - section: "section 1"
#        contents: index.md
#        
#          - href: "alaska-data-management-101"
#          
#      - section: "Section 2"
#        contents: auto
#        
#        contents:
#          - text: Plan
#            href: "planning"
#          
#      - section: "Acquire"
#        contents:
#          - auto: "acquire/*"
#        
#      - section: "Maintain"
#        contents: maintain
#        
#      - section: "Access & Share"
  navbar:
    right:
      - icon: github
        href: https://github.com/hmaier-fws/ak-dm-userguide
        text: GitHub Source
      - href: https://ak-region-dst.gitbook.io/alaska-region-interim-data-management-user-guide
        text: Original Site
        icon: tencent-qq

format:
  html:
#    theme: cerulean
#    smooth-scroll: true
    theme: default
    css: styles.css
    toc: true
    toc-title: TOC title
#    number-sections: true
#
#    other-links:
#      - text: Submit an issue
#        icon: github
#        href: https://github.com/hmaier-fws/ak-dm-userguide

# quarto preview --log log.txt --log-level info
# quarto preview source-files --log log.txt --log-level debug

#  latex:
#    toc: true
